### ISSUE TITLE
Does this allow multiple invites for a given resource?

### ISSUE THREAD

**Issue by krue-doug** [tomichj/invitation#21]
For example, if a person receives an invite from many users then the person can choose which one to accept. Would any of the other invites be invalid in favor of the newest one? `devise_invitable` creates a user after an invite is created, is this the case for `invitation` as well?

**Comment by tomichj** [comment]
There are several questions here, I'll try to unpack them and answer them clearly, but feel free to follow up.

`Invitation` does **not** create a user when the invite is created. An [Invitation](https://github.com/tomichj/invitation/blob/master/app/models/invite.rb) instance is created when you issue an invitation. The `Invitation` records the email address of the invitee, the sender, the resource the invitation is for, etc. 

When the user accepts the invitation, your user registration controller creates the user instance. Your user registration controller should include [Invitation::UserRegistration](https://github.com/tomichj/invitation/blob/master/lib/invitation/user_registration.rb) to assist in adding them to the resource they were invited to.

Issuing multiple invitations to a resource does not invalidate any of the previous invitations.

This project needs additional documentation. I'll try to add some over time.
