### ISSUE TITLE
Documentation: More info on the tables that will be created after db:migrate 

### ISSUE THREAD

**Issue by LizPrescott** [tomichj/invitation#23]
I have an invitation table already that might conflict, and it would be super helpful to get this info about your invitations table before I start hacking away.

**Comment by tomichj** [comment]
Here's the table created by `invitation`:

https://github.com/tomichj/invitation/blob/master/lib/generators/invitation/install/templates/db/migrate/create_invites.rb

**Comment by tomichj** [comment]
The table name, as you can see there, is `invites`, not `invitation`, so hopefully this won't cause a conflict for you.
